spring:
  datasource:
    url: jdbc:postgresql://84.201.162.28:5432/notifications
    username: admin
    password: VSAfg21SAVZx
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://84.201.162.28:5432/notifications
    username: admin
    password: VSAfg21SAVZx
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers:
      - 158.160.82.102:9091
      - 158.160.82.102:9092
      - 158.160.82.102:9093
    zookeeper:
      connect: 158.160.82.102:2181
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer